# Generated by Django 3.2.7 on 2021-11-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=15, unique=True, verbose_name='Description')),
                ('price', models.CharField(max_length=256, verbose_name='Price')),
                ('stock', models.FloatField(verbose_name='Stock')),
                ('unit_m', models.CharField(max_length=256, verbose_name='Unit_m')),
            ],
        ),
    ]
